# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "npm"

    directory: "/"

    schedule:
      interval: "daily"
      time: "04:00"

    open-pull-requests-limit: 10

    labels:
      - "dependencies"

    versioning-strategy: "increase"


    commit-message:
      include: "scope"
      prefix: "npm"

    rebase-strategy: "auto"

  - package-ecosystem: "github-actions"

    directory: "/"

    schedule:
      interval: "daily"
      time: "04:00"

    open-pull-requests-limit: 10

    labels:
      - "dependencies"

    target-branch: "master"

    commit-message:
      prefix: "github-actions"

    rebase-strategy: "auto"
