name: "Auto approve"

on:
  - pull_request_target

jobs:
  auto-approve:
    runs-on: "ubuntu-24.04"

    if: ${{ github.actor == 'dependabot[bot]' }}

    permissions:
      pull-requests: write

    steps:
      - uses: "fastify/github-action-merge-dependabot@v3"
        with:
          approve-only: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
